# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: LE-EZ-VS
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Tidy
      run: go mod tidy
      
    - name: BuildLinux
      run: go build -o ~/LEZVS-Linux/ -v ./...
      
    - name: BuildMacOS
      run: env GOOS=darwin GOARCH=amd64 go build -o ~/LEZVS-MacOS/ -v ./...
      
    - name: BuildWindows
      run: env GOOS=windows GOARCH=amd64 go build -o ~/LEZVS-Windows/ -v ./...
      
    - name: Upload Linux Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: LEZVS-Linux 
         # A file, directory or wildcard pattern that describes what to upload
        path: ~/LEZVS-Linux/
        if-no-files-found: error
        
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: LEZVS-Windows
         # A file, directory or wildcard pattern that describes what to upload
        path: ~/LEZVS-Windows/
        if-no-files-found: error
        
    - name: Upload MacOS Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: LEZVS-MacOS
         # A file, directory or wildcard pattern that describes what to upload
        path: ~/LEZVS-MacOS/
        if-no-files-found: error

